### ISSUE TITLE
OneTimeSecret Regions

### ISSUE THREAD

**Issue by IvanShires** [slashpass/onetimesecret-cli#1]
So OneTimeSecret added support for regions, ex. `us.onetimesecret.com`, `eu.onetimesecret.com`. It may be handy to add in a API request parameter to select which region you'd like to use.

Puedo code:
```
URL = "https://{{region}}.onetimesecret.com"

class OneTimeSecretCli(object):
    def create_link(self, secret, region="us",ttl=900):
        response = requests.post(
            "{}/api/v1/share".format(self.url),
            data={"secret": secret, "ttl": ttl},  # 900 ttl => 15 minutes
            auth=HTTPBasicAuth(self.user, self.key),
        )
```

**Comment by IvanShires** [comment]
In local environment, this works: 
```
response = requests.post("https://eu.onetimesecret.com/api/v1/share",
    data={"secret": secret, "ttl": ttl},  # 900 ttl => 15 minutes
    auth=HTTPBasicAuth(self.user, self.key),
)
```
Let me see if I can dabble some code together to make it a bit more inline with what was originally written.

**Comment by IvanShires** [comment]
Submitted https://github.com/slashpass/onetimesecret-cli/pull/2 - which may answer this problem.

**Comment by mtdb** [comment]
Thanks for the PR! Your changes are included in the latest published version
